services:

  devcontainer:
    build:
      context: .
      target: dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-{{ cookiecutter.python_version }}}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      - POETRY_PYPI_TOKEN_PYPI
    volumes:
      - ..:/workspaces
    {%- if cookiecutter.with_postgresql %}
    networks:
      - net
    {%- endif %}

  dev:
    extends: devcontainer
    stdin_open: true
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        "sudo chown user $$SSH_AUTH_SOCK && cp --update /opt/build/poetry/poetry.lock /workspaces/{{ cookiecutter.__project_name_kebab_case }}/ && mkdir -p /workspaces/{{ cookiecutter.__project_name_kebab_case }}/.git/hooks/ && cp --update /opt/build/git/* /workspaces/{{ cookiecutter.__project_name_kebab_case }}/.git/hooks/ && bash"
      ]
    environment:
      - POETRY_PYPI_TOKEN_PYPI
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    ports:
      - "8000"  # API port.
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/known_hosts:/home/user/.ssh/known_hosts
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock
    profiles:
      - dev

  api:
    build:
      context: .
      target: api
    tty: true
    restart: unless-stopped
    profiles:
      - api
  {%- if cookiecutter.with_postgresql %}
    networks:
      - net

  {{ cookiecutter.postgresql_server }}:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - {{ cookiecutter.postgresql_server }}:/var/lib/postgresql/data
    ports:
      - "{{ cookiecutter.postgresql_forward_port }}:5432"
    networks:
      - net
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
  {%- endif %}
  {%- if cookiecutter.with_adminer %}

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - {{ cookiecutter.postgresql_server }}
    ports:
      - "{{ cookiecutter.adminer_forward_port }}:8080"
    networks:
      - net
    environment:
      ADMINER_DEFAULT_SERVER: {{ cookiecutter.postgresql_server }}
  {%- endif %}
{%- if cookiecutter.with_postgresql %}

volumes:
  {{ cookiecutter.postgresql_server }}:

networks:
  net:
{%- endif %}
